const TAG_BLACKLIST = new Set([
  "", "hot", "new", "sale", "best", "top", "premium", "quality", "latest",
  "trending", "popular", "exclusive", "limited", "special",
])

const TAG_NORMALIZATION: [RegExp, string][] = [
  [/^#/, ""],
  [/[_\s]+/g, "-"],
  [/^-|-$/g, ""],
]

const TAG_DEDUP_MAP: [RegExp, string][] = [
  [/^smartwatch$/i, "smart-watch"],
  [/^smart\s*watch(es)?$/i, "smart-watch"],
  [/^smart\s*band$/i, "smart-band"],
  [/^smartband$/i, "smart-band"],
  [/^fitness\s*band$/i, "fitness-band"],
  [/^fitnessband$/i, "fitness-band"],
  [/^wireless\s*earbuds?$/i, "wireless-earbuds"],
  [/^airpods?$/i, "airpods"],
  [/^phone\s*case(s)?$/i, "phone-case"],
  [/^iphone\s*case(s)?$/i, "iphone-case"],
  [/^screen\s*protector$/i, "screen-protector"],
  [/^tempered\s*glass$/i, "tempered-glass"],
  [/^power\s*bank$/i, "power-bank"],
  [/^wireless\s*charger$/i, "wireless-charger"],
  [/^usb[-\s]*c$/i, "usb-c"],
  [/^bluetooth$/i, "bluetooth"],
  [/^bluetooth\s*calling$/i, "bluetooth-calling"],
  [/^amoled$/i, "amoled-display"],
  [/^amoled\s*display$/i, "amoled-display"],
  [/^heart.?rate/i, "heart-rate-monitor"],
  [/^spo2/i, "spo2-monitor"],
  [/^gps$/i, "gps-tracking"],
]

const FEATURE_KEYWORDS: [RegExp, string][] = [
  [/(?:amoled|oled|retina)\s*display/i, "amoled-display"],
  [/(?:heart.?rate|hr)\s*(?:monitor|sensor|track)/i, "heart-rate-monitor"],
  [/\bspo2\b/i, "spo2-monitor"],
  [/\bgps\b/i, "gps-tracking"],
  [/\bbluetooth\s*calling\b/i, "bluetooth-calling"],
  [/\bwireless\s*charging\b/i, "wireless-charging"],
  [/(?:fast|quick)\s*charging/i, "fast-charging"],
  [/\bwater\s*resist(?:ant|ance)\b/i, "water-resistant"],
  [/\bip[0-9]{2}\b/i, "water-resistant"],
  [/\banc\b/i, "noise-cancellation"],
  [/\bnoise\s*cancel/i, "noise-cancellation"],
  [/\b(?:long|extended)\s*battery/i, "long-battery-life"],
  [/\b(?:fitness|activity)\s*track/i, "fitness-tracker"],
  [/\bsleep\s*track/i, "sleep-tracking"],
  [/\b(?:drop|shock)\s*protect/i, "shockproof"],
  [/\bmilitary\s*grade/i, "military-grade"],
  [/\b(?:silicone|tpu|polycarbonate)\b/i, "silicone-case"],
  [/\b(?:woven|fabric)\b/i, "woven-case"],
  [/\bwireless\s*earbud/i, "wireless-earbuds"],
  [/\b(?:true\s*)?wireless/i, "wireless"],
]

export interface TagSuggestion {
  tags: string[]
  autoGenerated: string[]
}

export function normalizeTag(raw: string): string {
  let tag = raw.trim()
  for (const [pattern, replacement] of TAG_NORMALIZATION) {
    tag = tag.replace(pattern, replacement)
  }
  tag = tag.toLowerCase()
  return tag
}

export function deduplicateTags(tags: string[]): string[] {
  const seen = new Set<string>()
  const result: string[] = []

  for (const raw of tags) {
    const normalized = normalizeTag(raw)
    let finalTag = normalized

    for (const [pattern, replacement] of TAG_DEDUP_MAP) {
      if (pattern.test(normalized)) {
        finalTag = replacement
        break
      }
    }

    if (finalTag && !TAG_BLACKLIST.has(finalTag) && !seen.has(finalTag)) {
      seen.add(finalTag)
      result.push(finalTag)
    }
  }

  return result
}

export function parseTags(tagsCsv: string): string[] {
  if (!tagsCsv) return []
  return tagsCsv
    .split(",")
    .map((t) => t.trim())
    .filter(Boolean)
}

export function generateAutoTags(
  title: string,
  type: string,
  category: string,
  vendor: string,
  description: string,
  variantOptions: string[],
): string[] {
  const tags: string[] = []
  const text = `${title} ${type} ${category} ${vendor} ${description}`.toLowerCase()

  const titleWords = title
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .split(/\s+/)
    .filter((w) => w.length > 1)
    .slice(0, 4)

  const modelTags = titleWords
    .filter((w) => /^[a-z]+[-]?[0-9]+$/.test(w) || /^(series|pro|max|air|mini|lite|ultra)$/i.test(w))
    .map((w) => w.toLowerCase())

  tags.push(...modelTags)

  for (const [pattern, tag] of FEATURE_KEYWORDS) {
    if (pattern.test(text) && !tags.includes(tag)) {
      tags.push(tag)
    }
  }

  if (vendor) {
    const vTag = vendor.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "")
    if (vTag && !tags.includes(vTag)) tags.push(vTag)
  }

  return deduplicateTags(tags)
}

export function mergeTags(csvTags: string[], autoTags: string[]): string[] {
  const all = [...csvTags, ...autoTags]
  return deduplicateTags(all).slice(0, 15)
}
